### ISSUE TITLE
App is not configured

### ISSUE THREAD

**Issue by dallyh** [pauloamgomes/contentful-better-slugs-app#14]
Hello,

I'm having trouble getting this app to set up. I have my slug field where appearance is set to "better slugs", I have my Better Slugs app configured for the content type I want to use. However I still get this error:

![image](https://github.com/pauloamgomes/contentful-better-slugs-app/assets/6968534/c2603df4-5937-4af8-9b9e-ee86afab6349)

The slug pattern is configured:
![image](https://github.com/pauloamgomes/contentful-better-slugs-app/assets/6968534/282e647c-93ad-4b99-b2ee-f4fb91d296e7)

I tried many different things and I'm lost.

Thanks!

**Comment by dallyh** [comment]
My bad, the configuration was wrong. Had to triple check everything :)

**Comment by novaotica** [comment]
np, glad it's working 👍
