### ISSUE TITLE
[day] token adds a dot after the day number

### ISSUE THREAD

**Issue by dallyh** [pauloamgomes/contentful-better-slugs-app#15]
The title is self explanatory, please see this screenshot:

![image](https://github.com/pauloamgomes/contentful-better-slugs-app/assets/6968534/6c212b2f-0b1f-4db6-a637-0d44ceaa9a26)

Pattern used is `[day]-[day]-[year]-[month]-[day]-[field:title]` (for testing purposes).

![image](https://github.com/pauloamgomes/contentful-better-slugs-app/assets/6968534/db56a27c-395c-43b1-9942-7ae6a96225de)

**Comment by novaotica** [comment]
Hi @dallyh 
can you confirm you are using the latest released version?
I tried to replicate your issue but without success, it seems to work fine for me.

I used the same pattern:
<img width="926" alt="image" src="https://github.com/pauloamgomes/contentful-better-slugs-app/assets/142749605/9c9d24ac-63fe-451f-8bc2-173280657aa3">

<img width="809" alt="image" src="https://github.com/pauloamgomes/contentful-better-slugs-app/assets/142749605/3145ee3c-5629-452d-83d1-6ca61fe8e91b">


Also tried with Czech locale and no differences!

**Comment by pauloamgomes** [comment]
Hi @dallyh 
can you confirm you are using the latest released version? https://github.com/pauloamgomes/contentful-better-slugs-app/releases/tag/V1.0.1
I tried to replicate your issue but without success, it seems to work fine for me.

I used the same pattern:
<img width="926" alt="image" src="https://github.com/pauloamgomes/contentful-better-slugs-app/assets/142749605/9c9d24ac-63fe-451f-8bc2-173280657aa3">

<img width="809" alt="image" src="https://github.com/pauloamgomes/contentful-better-slugs-app/assets/142749605/3145ee3c-5629-452d-83d1-6ca61fe8e91b">


Also tried with Czech locale and no differences!

**Comment by dallyh** [comment]
Hi @pauloamgomes unfortunately I switched to a different CMS so currently I cannot really reproduce this. I'm going to close this issue for now.
