### ISSUE TITLE
TypeError Occurs and Slug Field Not Generated When Using Reference Field in Better Slugs Configurations

### ISSUE THREAD

**Issue by ShinjiroMuraoka** [pauloamgomes/contentful-better-slugs-app#16]
Hi,

I've installed and configured the app in my space following the instructions in the README. When using Better Slugs Configurations with `[fields:title]`, the slug generates as expected. However, specifying a Reference field like `[fields:category:name]` triggers an error: `TypeError: Expected a string, got "object",` and no value is output to the slug field. The category is a one-reference field.
![better-slug-issue](https://github.com/pauloamgomes/contentful-better-slugs-app/assets/80103436/44042e3e-87d6-47a9-8b8b-aaf1f7da253d)

Additionally, when setting up patterns like `[fields:title]/[fields:subtitle]`, the slug field remains empty unless both fields are filled in (triggering `TypeError: Expected a string, got "undefined"`).
![better-slug-issue_2](https://github.com/pauloamgomes/contentful-better-slugs-app/assets/80103436/bbe6f671-b355-4e13-81aa-944cfd9c9fb8)

After some investigation, it seems there might be an issue around the slugify function at or near line 226 in the following file: https://github.com/pauloamgomes/contentful-better-slugs-app/blob/main/src/locations/Field.tsx#L226

Is there any solution available for this problem?

**Comment by pauloamgomes** [comment]
Hi @ShinjiroMuraoka , thanks for catching this, it should be now fixed. Kindly let me know if it works for you.

**Comment by ShinjiroMuraoka** [comment]
Thanks for the response, @pauloamgomes .
The error when referencing the Reference field has been resolved, but the error when the field is empty continues to occur.
![202404041425](https://github.com/pauloamgomes/contentful-better-slugs-app/assets/80103436/31c72581-a16e-4979-9fec-db2a352870b6)

When I was using it in UI Extensions, empty fields were excluded and slugs were generated, so I would like to continue to achieve that usage if possible.

**Comment by pauloamgomes** [comment]
Should be fixed.
